// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjls2mK7caTySH8O_RetBCfga7uSTVNs8',
    appId: '1:739507463106:web:6514b5f0e4b59c49956c5b',
    messagingSenderId: '739507463106',
    projectId: 'school-management-system-3405d',
    authDomain: 'school-management-system-3405d.firebaseapp.com',
    databaseURL: 'https://school-management-system-3405d-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-system-3405d.firebasestorage.app',
    measurementId: 'G-FBT6ERW0M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIH2zligf9dVKl2txPFNN3eKtt4ZVXzeg',
    appId: '1:739507463106:android:9dc9e8067c151aa6956c5b',
    messagingSenderId: '739507463106',
    projectId: 'school-management-system-3405d',
    databaseURL: 'https://school-management-system-3405d-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-system-3405d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApE2YU00sutHQ4N7S2jPHt_SscvV6sJk4',
    appId: '1:739507463106:ios:949c3323320c9caf956c5b',
    messagingSenderId: '739507463106',
    projectId: 'school-management-system-3405d',
    databaseURL: 'https://school-management-system-3405d-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-system-3405d.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApE2YU00sutHQ4N7S2jPHt_SscvV6sJk4',
    appId: '1:739507463106:ios:949c3323320c9caf956c5b',
    messagingSenderId: '739507463106',
    projectId: 'school-management-system-3405d',
    databaseURL: 'https://school-management-system-3405d-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-system-3405d.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagmentSystem',
  );

}